name: Execute checks

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/checkout_submodules

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run check
        # This is a workaround for the failing migration actions. They fail due to a lack of sqlite driver. We currently have no migrations.
        # TODO: Remove this workaround when we have migrations.
        run: ./gradlew check -x verifyDebugDatabaseMigration -x verifyReleaseDatabaseMigration -x verifyMainDatabaseMigration --no-daemon

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
